export const mockEvents = [
  {
    id: '1',
    title: '周六混双友谊赛',
    description: '以双打练习为主，欢迎新朋友加入！赛后一起吃饭。',
    date: '2026-06-07',
    start_time: '09:00',
    end_time: '12:00',
    location: '阳光体育中心 3号馆',
    max_participants: 16,
    price: 30,
    level: 'intermediate',
    status: 'active',
    payment_method: 'wechat',
    wechat_qr: null,
    payid: '',
    account_name: '',
    bsb: '',
    account_number: '',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: '初学者入门训练营',
    description: '专为零基础球友设计，有专业教练指导握拍、步伐和基本技术。',
    date: '2026-06-08',
    start_time: '14:00',
    end_time: '16:00',
    location: '城北羽毛球馆',
    max_participants: 12,
    price: 50,
    level: 'beginner',
    status: 'active',
    payment_method: 'bank',
    wechat_qr: null,
    payid: 'duoduo@email.com',
    account_name: 'Duo Duo Sports',
    bsb: '063-000',
    account_number: '1234 5678',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: '周日自由拍练',
    description: '无固定安排，大家自由对打，平摊场地费即可。',
    date: '2026-06-14',
    start_time: '19:00',
    end_time: '21:30',
    location: '汇德羽毛球俱乐部',
    max_participants: 20,
    price: 25,
    level: 'all',
    status: 'active',
    payment_method: 'wechat',
    wechat_qr: null,
    payid: '',
    account_name: '',
    bsb: '',
    account_number: '',
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: '高水平单打挑战赛',
    description: '单打对抗，积分制赛制，胜者组和败者组双循环。',
    date: '2026-06-15',
    start_time: '10:00',
    end_time: '14:00',
    location: '精英体育馆 VIP馆',
    max_participants: 8,
    price: 0,
    level: 'advanced',
    status: 'active',
    payment_method: 'free',
    wechat_qr: null,
    payid: '',
    account_name: '',
    bsb: '',
    account_number: '',
    created_at: new Date().toISOString(),
  },
]

export const mockRegistrations = {
  '1': [
    { id: 'r1', event_id: '1', name: '小明', gender: 'male', skill_level: '4', quantity: 1, notes: '', payment_status: 'confirmed', payment_screenshot: null, created_at: new Date().toISOString() },
    { id: 'r2', event_id: '1', name: '阿杰', gender: 'male', skill_level: '5', quantity: 2, notes: '带朋友一起', payment_status: 'confirmed', payment_screenshot: null, created_at: new Date().toISOString() },
    { id: 'r3', event_id: '1', name: '晓燕', gender: 'female', skill_level: '3', quantity: 1, notes: '', payment_status: 'pending', payment_screenshot: null, created_at: new Date().toISOString() },
  ],
  '2': [
    { id: 'r4', event_id: '2', name: '小红', gender: 'female', skill_level: '1', quantity: 1, notes: '完全零基础', payment_status: 'confirmed', payment_screenshot: null, created_at: new Date().toISOString() },
  ],
  '3': [],
  '4': [
    { id: 'r5', event_id: '4', name: '阿强', gender: 'male', skill_level: '6', quantity: 1, notes: '', payment_status: 'confirmed', payment_screenshot: null, created_at: new Date().toISOString() },
    { id: 'r6', event_id: '4', name: '大伟', gender: 'male', skill_level: '6', quantity: 1, notes: '', payment_status: 'pending', payment_screenshot: null, created_at: new Date().toISOString() },
  ],
}
